// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as publicapi$0 from "../../../internal/publicapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modsync$0 from "../modsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serverlist$0 from "../serverlist/models.js";

export class GameInfo {
    "dir": string;
    "found": boolean;
    "detected": boolean;
    "version": string;

    /** Creates a new GameInfo instance. */
    constructor($$source: Partial<GameInfo> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GameInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameInfo($$parsedSource as Partial<GameInfo>);
    }
}

export class Phase {
    "serverId": string;
    "phase": string;
    "message"?: string;

    /** Creates a new Phase instance. */
    constructor($$source: Partial<Phase> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Phase instance from a string or object.
     */
    static createFrom($$source: any = {}): Phase {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Phase($$parsedSource as Partial<Phase>);
    }
}

/**
 * PlayRequest logs in with a saved account (AccountID) or a login typed for this launch.
 */
export class PlayRequest {
    "accountId": number;
    "username": string;
    "password": string;
    "serverPassword": string;
    "takeOver": boolean;

    /** Creates a new PlayRequest instance. */
    constructor($$source: Partial<PlayRequest> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("serverPassword" in $$source)) {
            this["serverPassword"] = "";
        }
        if (!("takeOver" in $$source)) {
            this["takeOver"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayRequest($$parsedSource as Partial<PlayRequest>);
    }
}

export class Status {
    "id": string;
    "reachable": boolean;
    "error"?: string;
    "hasModPage": boolean;
    "status"?: string;
    "statusMessage"?: string;
    "players"?: number | null;
    "connect"?: publicapi$0.PublicConnect | null;
    "gameVersion"?: string;
    "modCount": number;
    "plan": modsync$0.Plan;
    "saved"?: serverlist$0.Server | null;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("hasModPage" in $$source)) {
            this["hasModPage"] = false;
        }
        if (!("modCount" in $$source)) {
            this["modCount"] = 0;
        }
        if (!("plan" in $$source)) {
            this["plan"] = (new modsync$0.Plan());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField7_0 = $$createType1;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connect" in $$parsedSource) {
            $$parsedSource["connect"] = $$createField7_0($$parsedSource["connect"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField10_0($$parsedSource["plan"]);
        }
        if ("saved" in $$parsedSource) {
            $$parsedSource["saved"] = $$createField11_0($$parsedSource["saved"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

export class SyncProgress {
    "serverId": string;
    "index": number;
    "total": number;
    "title": string;
    "bytes": number;
    "size": number;

    /** Creates a new SyncProgress instance. */
    constructor($$source: Partial<SyncProgress> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncProgress($$parsedSource as Partial<SyncProgress>);
    }
}

// Private type creation functions
const $$createType0 = publicapi$0.PublicConnect.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = modsync$0.Plan.createFrom;
const $$createType3 = serverlist$0.Server.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
