// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serverlist$0 from "../serverlist/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddServerURL(raw: string): $CancellablePromise<config$0.Server> {
    return $Call.ByID(1173903478, raw).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AutoConnect is on unless the player turned it off.
 */
export function AutoConnect(): $CancellablePromise<boolean> {
    return $Call.ByID(3981932562);
}

export function Game(): $CancellablePromise<$models.GameInfo> {
    return $Call.ByID(1485398853).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportSaved(savedID: number, pageURL: string): $CancellablePromise<config$0.Server> {
    return $Call.ByID(2628391053, savedID, pageURL).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Play(id: string, req: $models.PlayRequest): $CancellablePromise<void> {
    return $Call.ByID(863747965, id, req);
}

export function RemoveServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(2167815728, id);
}

export function SavedServers(): $CancellablePromise<serverlist$0.Server[]> {
    return $Call.ByID(3161420858).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Servers(): $CancellablePromise<config$0.Server[]> {
    return $Call.ByID(3350380661).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetAutoConnect(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3864618004, on);
}

export function SetGameDir(dir: string): $CancellablePromise<$models.GameInfo> {
    return $Call.ByID(3137641654, dir).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartGame(id: string, takeOver: boolean): $CancellablePromise<void> {
    return $Call.ByID(2343384167, id, takeOver);
}

export function Status(id: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(1032378105, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Sync(id: string, takeOver: boolean): $CancellablePromise<void> {
    return $Call.ByID(2830436296, id, takeOver);
}

export function UpdateServer(id: string, name: string, host: string, port: number, account: string): $CancellablePromise<config$0.Server> {
    return $Call.ByID(1015876025, id, name, host, port, account).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Server.createFrom;
const $$createType1 = $models.GameInfo.createFrom;
const $$createType2 = serverlist$0.Server.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.Status.createFrom;
