// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(833371355);
}

export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3935949939).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ChooseFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(1337902351, title);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(790318107, url);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1828333558);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
