// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateInfo {
    "available": boolean;
    "version": string;
    "url": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
