// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Backup struct {
	ID          int64
	File        string
	CreatedAt   int64
	Size        int64
	Fingerprint string
	Reason      string
	Note        string
	Pinned      bool
	BuildID     string
	FileCount   int64
	ModCount    int64
}

type ModEntry struct {
	WorkshopID string
	ModID      string
	Enabled    bool
	Position   int64
}

type Schedule struct {
	ID          int64
	Name        string
	Action      string
	Cron        string
	Message     string
	WarnMinutes string
	Enabled     bool
	CreatedAt   int64
	LastRunAt   int64
	LastResult  string
}

type Setting struct {
	Key   string
	Value string
}

type TrackedItem struct {
	WorkshopID    string
	Title         string
	Position      int64
	AddedAt       int64
	RemoteUpdated int64
	FileSize      int64
	PreviewUrl    string
	CheckedAt     int64
}
