// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const addItem = `-- name: AddItem :execrows
INSERT INTO tracked_items(workshop_id, position, added_at)
VALUES(?, (SELECT COALESCE(MAX(position), 0) + 1 FROM tracked_items), ?)
ON CONFLICT DO NOTHING
`

type AddItemParams struct {
	WorkshopID string
	AddedAt    int64
}

// AddItem appends at the end of the list; an existing item is left untouched.
func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addItem, arg.WorkshopID, arg.AddedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSchedule = `-- name: CreateSchedule :execlastid
INSERT INTO schedules(name, action, cron, message, warn_minutes, enabled, created_at)
VALUES(?, ?, ?, ?, ?, ?, ?)
`

type CreateScheduleParams struct {
	Name        string
	Action      string
	Cron        string
	Message     string
	WarnMinutes string
	Enabled     bool
	CreatedAt   int64
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSchedule,
		arg.Name,
		arg.Action,
		arg.Cron,
		arg.Message,
		arg.WarnMinutes,
		arg.Enabled,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBackup, id)
	return err
}

const deleteModEntry = `-- name: DeleteModEntry :exec
DELETE FROM mod_entries WHERE workshop_id = ? AND mod_id = ?
`

type DeleteModEntryParams struct {
	WorkshopID string
	ModID      string
}

func (q *Queries) DeleteModEntry(ctx context.Context, arg DeleteModEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteModEntry, arg.WorkshopID, arg.ModID)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSchedule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureModEntry = `-- name: EnsureModEntry :exec
INSERT INTO mod_entries(workshop_id, mod_id, enabled, position)
VALUES(?, ?, ?, (SELECT COALESCE(MAX(position), 0) + 1 FROM mod_entries))
ON CONFLICT DO NOTHING
`

type EnsureModEntryParams struct {
	WorkshopID string
	ModID      string
	Enabled    bool
}

func (q *Queries) EnsureModEntry(ctx context.Context, arg EnsureModEntryParams) error {
	_, err := q.db.ExecContext(ctx, ensureModEntry, arg.WorkshopID, arg.ModID, arg.Enabled)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, file, created_at, size, fingerprint, reason, note, pinned, build_id, file_count, mod_count FROM backups WHERE id = ?
`

func (q *Queries) GetBackup(ctx context.Context, id int64) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.File,
		&i.CreatedAt,
		&i.Size,
		&i.Fingerprint,
		&i.Reason,
		&i.Note,
		&i.Pinned,
		&i.BuildID,
		&i.FileCount,
		&i.ModCount,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, name, "action", cron, message, warn_minutes, enabled, created_at, last_run_at, last_result FROM schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Action,
		&i.Cron,
		&i.Message,
		&i.WarnMinutes,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastRunAt,
		&i.LastResult,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertBackup = `-- name: InsertBackup :execlastid
INSERT INTO backups(file, created_at, size, fingerprint, reason, note, pinned, build_id, file_count, mod_count)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBackupParams struct {
	File        string
	CreatedAt   int64
	Size        int64
	Fingerprint string
	Reason      string
	Note        string
	Pinned      bool
	BuildID     string
	FileCount   int64
	ModCount    int64
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertBackup,
		arg.File,
		arg.CreatedAt,
		arg.Size,
		arg.Fingerprint,
		arg.Reason,
		arg.Note,
		arg.Pinned,
		arg.BuildID,
		arg.FileCount,
		arg.ModCount,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const latestBackup = `-- name: LatestBackup :one
SELECT id, file, created_at, size, fingerprint, reason, note, pinned, build_id, file_count, mod_count FROM backups ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) LatestBackup(ctx context.Context) (Backup, error) {
	row := q.db.QueryRowContext(ctx, latestBackup)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.File,
		&i.CreatedAt,
		&i.Size,
		&i.Fingerprint,
		&i.Reason,
		&i.Note,
		&i.Pinned,
		&i.BuildID,
		&i.FileCount,
		&i.ModCount,
	)
	return i, err
}

const listBackups = `-- name: ListBackups :many
SELECT id, file, created_at, size, fingerprint, reason, note, pinned, build_id, file_count, mod_count FROM backups ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBackups(ctx context.Context) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.File,
			&i.CreatedAt,
			&i.Size,
			&i.Fingerprint,
			&i.Reason,
			&i.Note,
			&i.Pinned,
			&i.BuildID,
			&i.FileCount,
			&i.ModCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT workshop_id, title, position, added_at, remote_updated, file_size, preview_url, checked_at FROM tracked_items ORDER BY position, added_at, workshop_id
`

func (q *Queries) ListItems(ctx context.Context) ([]TrackedItem, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackedItem{}
	for rows.Next() {
		var i TrackedItem
		if err := rows.Scan(
			&i.WorkshopID,
			&i.Title,
			&i.Position,
			&i.AddedAt,
			&i.RemoteUpdated,
			&i.FileSize,
			&i.PreviewUrl,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModEntries = `-- name: ListModEntries :many
SELECT workshop_id, mod_id, enabled, position FROM mod_entries ORDER BY position, workshop_id, mod_id
`

func (q *Queries) ListModEntries(ctx context.Context) ([]ModEntry, error) {
	rows, err := q.db.QueryContext(ctx, listModEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModEntry{}
	for rows.Next() {
		var i ModEntry
		if err := rows.Scan(
			&i.WorkshopID,
			&i.ModID,
			&i.Enabled,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, "action", cron, message, warn_minutes, enabled, created_at, last_run_at, last_result FROM schedules ORDER BY id
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.Cron,
			&i.Message,
			&i.WarnMinutes,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastRunAt,
			&i.LastResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings(key, value) VALUES(?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type PutSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting, arg.Key, arg.Value)
	return err
}

const recordScheduleRun = `-- name: RecordScheduleRun :exec
UPDATE schedules SET last_run_at = ?, last_result = ? WHERE id = ?
`

type RecordScheduleRunParams struct {
	LastRunAt  int64
	LastResult string
	ID         int64
}

func (q *Queries) RecordScheduleRun(ctx context.Context, arg RecordScheduleRunParams) error {
	_, err := q.db.ExecContext(ctx, recordScheduleRun, arg.LastRunAt, arg.LastResult, arg.ID)
	return err
}

const removeItem = `-- name: RemoveItem :execrows
DELETE FROM tracked_items WHERE workshop_id = ?
`

func (q *Queries) RemoveItem(ctx context.Context, workshopID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeItem, workshopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setBackupPinned = `-- name: SetBackupPinned :execrows
UPDATE backups SET pinned = ? WHERE id = ?
`

type SetBackupPinnedParams struct {
	Pinned bool
	ID     int64
}

func (q *Queries) SetBackupPinned(ctx context.Context, arg SetBackupPinnedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBackupPinned, arg.Pinned, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setModEnabled = `-- name: SetModEnabled :execrows
UPDATE mod_entries SET enabled = ? WHERE workshop_id = ? AND mod_id = ?
`

type SetModEnabledParams struct {
	Enabled    bool
	WorkshopID string
	ModID      string
}

func (q *Queries) SetModEnabled(ctx context.Context, arg SetModEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setModEnabled, arg.Enabled, arg.WorkshopID, arg.ModID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setModPosition = `-- name: SetModPosition :exec
UPDATE mod_entries SET position = ? WHERE mod_id = ?
`

type SetModPositionParams struct {
	Position int64
	ModID    string
}

func (q *Queries) SetModPosition(ctx context.Context, arg SetModPositionParams) error {
	_, err := q.db.ExecContext(ctx, setModPosition, arg.Position, arg.ModID)
	return err
}

const shiftModPositions = `-- name: ShiftModPositions :exec
UPDATE mod_entries SET position = position + 1000000
`

func (q *Queries) ShiftModPositions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, shiftModPositions)
	return err
}

const updateItemRemote = `-- name: UpdateItemRemote :exec
UPDATE tracked_items SET title = ?, remote_updated = ?, file_size = ?, preview_url = ?, checked_at = ?
WHERE workshop_id = ?
`

type UpdateItemRemoteParams struct {
	Title         string
	RemoteUpdated int64
	FileSize      int64
	PreviewUrl    string
	CheckedAt     int64
	WorkshopID    string
}

func (q *Queries) UpdateItemRemote(ctx context.Context, arg UpdateItemRemoteParams) error {
	_, err := q.db.ExecContext(ctx, updateItemRemote,
		arg.Title,
		arg.RemoteUpdated,
		arg.FileSize,
		arg.PreviewUrl,
		arg.CheckedAt,
		arg.WorkshopID,
	)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :execrows
UPDATE schedules SET name = ?, action = ?, cron = ?, message = ?, warn_minutes = ?, enabled = ?
WHERE id = ?
`

type UpdateScheduleParams struct {
	Name        string
	Action      string
	Cron        string
	Message     string
	WarnMinutes string
	Enabled     bool
	ID          int64
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Name,
		arg.Action,
		arg.Cron,
		arg.Message,
		arg.WarnMinutes,
		arg.Enabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
