//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../../magne4000/easy-pz-docker/launcher/internal/core/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "play:phase": $$createType0,
        "sync:progress": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = core$0.Phase.createFrom;
const $$createType1 = core$0.SyncProgress.createFrom;

configure();
