// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as publicapi$0 from "../../../internal/publicapi/models.js";

export class Plan {
    "download": publicapi$0.PublicItem[];
    "bytes": number;
    "upToDate": number;

    /**
     * Foreign: existing folders the launcher did not install.
     */
    "foreign": string[];

    /** Creates a new Plan instance. */
    constructor($$source: Partial<Plan> = {}) {
        if (!("download" in $$source)) {
            this["download"] = [];
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("upToDate" in $$source)) {
            this["upToDate"] = 0;
        }
        if (!("foreign" in $$source)) {
            this["foreign"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     */
    static createFrom($$source: any = {}): Plan {
        const $$createField0_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("download" in $$parsedSource) {
            $$parsedSource["download"] = $$createField0_0($$parsedSource["download"]);
        }
        if ("foreign" in $$parsedSource) {
            $$parsedSource["foreign"] = $$createField3_0($$parsedSource["foreign"]);
        }
        return new Plan($$parsedSource as Partial<Plan>);
    }
}

// Private type creation functions
const $$createType0 = publicapi$0.PublicItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
