// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PublicConnect is omitted when neither PANEL_PUBLIC_GAME_ADDRESS nor
 * PANEL_PUBLIC_URL is set.
 */
export class PublicConnect {
    "host": string;
    "port": number;

    /** Creates a new PublicConnect instance. */
    constructor($$source: Partial<PublicConnect> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicConnect instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicConnect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicConnect($$parsedSource as Partial<PublicConnect>);
    }
}

export class PublicItem {
    "workshopId": string;
    "title": string;
    "url": string;
    "size": number;
    "timeUpdated"?: string;
    "mods": PublicMod[];
    "download": PublicPack;

    /** Creates a new PublicItem instance. */
    constructor($$source: Partial<PublicItem> = {}) {
        if (!("workshopId" in $$source)) {
            this["workshopId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mods" in $$source)) {
            this["mods"] = [];
        }
        if (!("download" in $$source)) {
            this["download"] = (new PublicPack());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicItem instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicItem {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mods" in $$parsedSource) {
            $$parsedSource["mods"] = $$createField5_0($$parsedSource["mods"]);
        }
        if ("download" in $$parsedSource) {
            $$parsedSource["download"] = $$createField6_0($$parsedSource["download"]);
        }
        return new PublicItem($$parsedSource as Partial<PublicItem>);
    }
}

export class PublicMod {
    "id": string;
    "name": string;
    "folder": string;

    /** Creates a new PublicMod instance. */
    constructor($$source: Partial<PublicMod> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicMod instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicMod($$parsedSource as Partial<PublicMod>);
    }
}

export class PublicPack {
    "url": string;
    "ready": boolean;
    "size": number;
    "sha256": string;
    "error"?: string;

    /** Creates a new PublicPack instance. */
    constructor($$source: Partial<PublicPack> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicPack instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicPack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicPack($$parsedSource as Partial<PublicPack>);
    }
}

// Private type creation functions
const $$createType0 = PublicMod.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PublicPack.createFrom;
