// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Account {
    "id": number;
    "username": string;
    "savePassword": boolean;

    /**
     * AuthType 1 is password only; others need a second factor.
     */
    "authType": number;
    "lastLogon": string;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("savePassword" in $$source)) {
            this["savePassword"] = false;
        }
        if (!("authType" in $$source)) {
            this["authType"] = 0;
        }
        if (!("lastLogon" in $$source)) {
            this["lastLogon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

export class Server {
    "id": number;
    "name": string;
    "ip": string;
    "port": number;
    "description": string;
    "accounts": Account[];

    /** Creates a new Server instance. */
    constructor($$source: Partial<Server> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     */
    static createFrom($$source: any = {}): Server {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField5_0($$parsedSource["accounts"]);
        }
        return new Server($$parsedSource as Partial<Server>);
    }
}

// Private type creation functions
const $$createType0 = Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
